# Generated by Django 2.2.2 on 2019-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='time_published',
            field=models.DateTimeField(verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(default=''),
        ),
    ]
