# Generated by Django 2.2.2 on 2019-06-20 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190619_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='time_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 17, 0, 4, 383284), verbose_name='date published'),
        ),
    ]
