# Generated by Django 2.2.2 on 2020-04-01 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190620_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='time_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 22, 1, 56, 349), verbose_name='date published'),
        ),
    ]
