# Generated by Django 2.2.2 on 2020-04-01 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200401_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='time_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 23, 34, 1, 301771), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='tutorial_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorialCategory', verbose_name='Category'),
        ),
    ]
