# Generated by Django 2.2.2 on 2020-04-01 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200401_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='time_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 0, 2, 41, 182893), verbose_name='date published'),
        ),
    ]
